# Configurations
title:            Title
longtitle:        Long Title
author:           Angga Bayu Prakhosha
email:            anggaprakhosha@gmail.com
#description: >

url:              'https://prakhosha.github.io'
#baseurl:          '/jekyll-gitbook'

remote_theme : aterenin/minima-reboot

toc:
    enabled: true
    h_min: 1
    h_max: 3
